// ===== IJARA HUB — MA'LUMOTLAR BAZASI =====
const LISTINGS = [
    {
        id: 1,
        title: "Zamonaviy 2 xonali kvartira",
        category: "uy",
        categoryLabel: "🏠 Uylar",
        price: 250000,
        priceType: "kunlik",
        location: "Toshkent, Chilonzor",
        rating: 4.8,
        reviews: 34,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
        owner: "Aziz Karimov",
        ownerImg: "https://i.pravatar.cc/60?img=11",
        verified: true,
        premium: true,
        description: "Markazda joylashgan, to'liq jihozlangan zamonaviy kvartira. Oshxona, yotoqxona, mehmonxona, wifi, konditsioner mavjud. Oilaviy yoki biznes safar uchun ideal.",
        features: ["WiFi", "Konditsioner", "Parkovka", "To'liq jihozlangan oshxona", "Lift"],
        available: true,
        minDays: 1,
        deposit: 500000
    },
    {
        id: 2,
        title: "Toyota Camry 2022 — Ijara",
        category: "mashina",
        categoryLabel: "🚗 Mashinalar",
        price: 350000,
        priceType: "kunlik",
        location: "Toshkent, Yunusobod",
        rating: 4.9,
        reviews: 58,
        image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&q=80",
        owner: "Bobur Yusupov",
        ownerImg: "https://i.pravatar.cc/60?img=22",
        verified: true,
        premium: true,
        description: "2022 yil Toyota Camry. Avtomatik uzatmalar qutisi, deri salon, isitiluvchi o'rindiqlar. Haydovchisiz yoki haydovchi bilan beriladi. Sug'urta qilingan.",
        features: ["Avtomat", "Deri salon", "Sug'urta", "GPS", "Haydovchi bilan"],
        available: true,
        minDays: 1,
        deposit: 1000000
    },
    {
        id: 3,
        title: "Sony A7III Professional Kamera",
        category: "texnika",
        categoryLabel: "🔌 Texnika",
        price: 150000,
        priceType: "kunlik",
        location: "Toshkent, Mirzo Ulug'bek",
        rating: 4.7,
        reviews: 21,
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
        owner: "Shahzod Mirzo",
        ownerImg: "https://i.pravatar.cc/60?img=33",
        verified: true,
        premium: false,
        description: "Sony A7III to'liq kadrli professional kamera. Barcha zarur linzalar, tripod va sumka bilan birga beriladi. Foto/video ishlar uchun ideal.",
        features: ["24-105mm linza", "85mm portret linza", "Tripod", "Flash", "Sumka"],
        available: true,
        minDays: 1,
        deposit: 300000
    },
    {
        id: 4,
        title: "Samarqandda 3 xonali uy",
        category: "uy",
        categoryLabel: "🏠 Uylar",
        price: 180000,
        priceType: "kunlik",
        location: "Samarqand, Markaz",
        rating: 4.6,
        reviews: 45,
        image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80",
        owner: "Malika Rahimova",
        ownerImg: "https://i.pravatar.cc/60?img=44",
        verified: true,
        premium: false,
        description: "Samarqand markazida, tarixiy joylarga yaqin qulay uy. Hovli, barbekyu, 3 yotoqxona, 2 hammom. Oilaviy dam olish uchun ajoyib.",
        features: ["Hovli", "Barbekyu", "WiFi", "3 yotoqxona", "Parkovka"],
        available: true,
        minDays: 2,
        deposit: 400000
    },
    {
        id: 5,
        title: "DJI Mavic Pro 3 Drone",
        category: "texnika",
        categoryLabel: "🔌 Texnika",
        price: 200000,
        priceType: "kunlik",
        location: "Toshkent, Shayxontohur",
        rating: 4.8,
        reviews: 16,
        image: "https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600&q=80",
        owner: "Firdavs Toshev",
        ownerImg: "https://i.pravatar.cc/60?img=55",
        verified: false,
        premium: false,
        description: "DJI Mavic Pro 3 professional drone. 4K video, 46 daqiqa uchish vaqti. 3 ta batareya, operator bilan yoki mustaqil bron qilish mumkin.",
        features: ["4K kamera", "3 batareya", "Portativ sumka", "Operator (ixtiyoriy)", "Sug'urta"],
        available: true,
        minDays: 1,
        deposit: 500000
    },
    {
        id: 6,
        title: "Toyotа Hiace — Mikroavtobus",
        category: "mashina",
        categoryLabel: "🚗 Mashinalar",
        price: 600000,
        priceType: "kunlik",
        location: "Toshkent, Bektemir",
        rating: 4.5,
        reviews: 29,
        image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80",
        owner: "Ulugbek Nazarov",
        ownerImg: "https://i.pravatar.cc/60?img=66",
        verified: true,
        premium: false,
        description: "16 o'rindiqli Toyota Hiace mikroavtobus. Guruh sayohatlari, to'y va tadbirlar uchun. Haydovchi bilan yoki ulash. Barcha hujjatlar to'liq.",
        features: ["16 o'rindiq", "Konditsioner", "Haydovchi bilan", "Sug'urta", "GPS"],
        available: true,
        minDays: 1,
        deposit: 1500000
    },
    {
        id: 7,
        title: "Dizaynli Ofis Kursisi (10 dona)",
        category: "mebel",
        categoryLabel: "🪑 Mebel",
        price: 50000,
        priceType: "kunlik",
        location: "Toshkent, Olmazor",
        rating: 4.3,
        reviews: 8,
        image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",
        owner: "Nodira Saidova",
        ownerImg: "https://i.pravatar.cc/60?img=77",
        verified: true,
        premium: false,
        description: "Zamonaviy ergonomik ofis kursisi 10 donasi birga. Konferensiyalar, seminarlar uchun ideal. Yetkazib berish va olib ketish xizmati mavjud.",
        features: ["10 dona", "Ergonomik", "Yetkazib berish", "O'rnatish", "Olib ketish"],
        available: true,
        minDays: 1,
        deposit: 200000
    },
    {
        id: 8,
        title: "To'y Üchün Tent va Stol-Stullar",
        category: "tadbir",
        categoryLabel: "🎉 Tadbir jihozlari",
        price: 800000,
        priceType: "kunlik",
        location: "Toshkent, Sergeli",
        rating: 4.7,
        reviews: 52,
        image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&q=80",
        owner: "Kamol Ergashev",
        ownerImg: "https://i.pravatar.cc/60?img=88",
        verified: true,
        premium: true,
        description: "200 kishilik to'y uchun to'liq jihozlar: katta tent, 200 stul, 20 stol, bezaklar, chiroqlar. O'rnatish va yig'ib olish xizmati bepul.",
        features: ["200 kishilik", "Tent", "Stol-stullar", "Bezaklar", "O'rnatish bepul"],
        available: true,
        minDays: 1,
        deposit: 2000000
    },
    {
        id: 9,
        title: "Toshkentda Ofis Xonasi",
        category: "uy",
        categoryLabel: "🏠 Uylar",
        price: 300000,
        priceType: "kunlik",
        location: "Toshkent, Yakkasaroy",
        rating: 4.6,
        reviews: 19,
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
        owner: "Dilnoza Hasanova",
        ownerImg: "https://i.pravatar.cc/60?img=99",
        verified: true,
        premium: false,
        description: "Toshkent markazida zamonaviy ofis xonasi. Mi'yori biznes uchlar uchun. WiFi, projetor, konditsioner. Soatlik yoki kunlik.",
        features: ["WiFi tez", "Projektor", "Konditsioner", "Retsepsiya", "Xavfsizlik"],
        available: true,
        minDays: 1,
        deposit: 300000
    },
    {
        id: 10,
        title: "Chevrolet Equinox 2023",
        category: "mashina",
        categoryLabel: "🚗 Mashinalar",
        price: 400000,
        priceType: "kunlik",
        location: "Toshkent, Uchtepa",
        rating: 4.9,
        reviews: 37,
        image: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=600&q=80",
        owner: "Jasur Xolmatov",
        ownerImg: "https://i.pravatar.cc/60?img=10",
        verified: true,
        premium: true,
        description: "2023 yilgi Chevrolet Equinox. Krossover, yaxshi yo'l o'tkazuvchanligi. Sug'urtalangan, GPS bor. Shahar va yo'l sayohati uchun ideal.",
        features: ["AWD", "GPS", "Sug'urta", "Yoqilg'i bilan", "Avtomat"],
        available: true,
        minDays: 1,
        deposit: 1200000
    },
    {
        id: 11,
        title: "Proyektor + Ekran",
        category: "texnika",
        categoryLabel: "🔌 Texnika",
        price: 80000,
        priceType: "kunlik",
        location: "Toshkent, Mirzo Ulug'bek",
        rating: 4.4,
        reviews: 28,
        image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80",
        owner: "Ravshan Qodirov",
        ownerImg: "https://i.pravatar.cc/60?img=12",
        verified: false,
        premium: false,
        description: "Full HD proyektor va 3 metrlik ko'chirma ekran. Prezentatsiyalar, kinotun va tadbirlar uchun. Barcha ulagichlar bilan ta'minlangan.",
        features: ["Full HD", "3m ekran", "HDMI/USB", "Dinamik", "Yetkazib berish"],
        available: true,
        minDays: 1,
        deposit: 150000
    },
    {
        id: 12,
        title: "Buxoro — Tarixiy Uy (Bed & Breakfast)",
        category: "uy",
        categoryLabel: "🏠 Uylar",
        price: 220000,
        priceType: "kunlik",
        location: "Buxoro, Eski shahar",
        rating: 4.9,
        reviews: 88,
        image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=600&q=80",
        owner: "Muazzam Xo'jayeva",
        ownerImg: "https://i.pravatar.cc/60?img=13",
        verified: true,
        premium: true,
        description: "Buxoro eski shahrida 200 yillik tarixiy hujra. Autentik o'zbek milliy uslubida. Nonushta kiritilgan. Sayyohlar uchun maxsus narx.",
        features: ["Tarixiy bino", "Nonushta", "WiFi", "Hovli", "Ekskursiya"],
        available: true,
        minDays: 2,
        deposit: 400000
    }
];

// Format price
function formatPrice(price) {
    return price.toLocaleString('uz-UZ') + " so'm";
}
